version: 2
jobs:
  build:
    branches:
      #only:
      #  - master
      #  - /[0-9]\.[0-9]\.[0-9]/
      ignore:
        - /dev-.*/

    docker:
      - image: circleci/golang:1.9

    working_directory: /go/src/github.com/tmtk75/weque

    steps:
      - checkout

      - restore_cache:
          keys:
            - v{{ .Environment.CIRCLE_CACHE_VERSION }}-{{ .Branch }}-{{ .Environment.CIRCLE_JOB }}-{{ checksum "Gopkg.lock" }}

      #- run: go get github.com/mitchellh/gox
      #- run: go get github.com/tcnksm/ghr
      - run: go get github.com/golang/dep/cmd/dep

      - save_cache:
          key: v{{ .Environment.CIRCLE_CACHE_VERSION }}-{{ .Branch }}-{{ .Environment.CIRCLE_JOB }}-{{ checksum "Gopkg.lock" }}
          paths:
            - vendor

      - run: dep ensure

      - run: make build

      - run:
          name: test
          command: |
            #mkdir -p test-reports
            #go test -v . | tee ./test-reports/reports.txt
            #make test
            go test -v ./...

      #- run: make release-binaries

      #- store_artifacts:
      #    path: ./pkg
      #    destination: pkg

      #- store_artifacts:
      #    path: pkg
      #    destination: nightly-build

      #- deploy:
      #    command: |
      #      if [ "${CIRCLE_BRANCH}" == "master" ]; then
      #        rm -rf pkg/dist/hoko
      #        version=`git describe --tag`-${CIRCLE_BUILD_NUM}
      #        ghr -u tmtk75 ${version} pkg/dist
      #      fi

